### ISSUE TITLE
make fails due to missing ~/.kbb/secrets/client_secret.json

### ISSUE THREAD

**Issue by dset0x** [danobi/kbb#2]
The only step where I've deviated from the default installation was that I installed the latest nsf/termbox from git instead of the one from the `requirements.txt` file.

```
$ make
python3 -m gui.gui
Traceback (most recent call last):
  File "/home/username/src/kbb/venv/lib/python3.4/site-packages/oauth2client/clientsecrets.py", line 122, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.kbb/secrets/client_secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/src/kbb/gui/gui.py", line 165, in <module>
    main()
  File "/home/username/src/kbb/gui/gui.py", line 128, in main
    g = GUI()
  File "/home/username/src/kbb/gui/gui.py", line 119, in __init__
    self.kb_board = kbb.Kbb()
  File "/home/username/src/kbb/kbb/kbb.py", line 542, in __init__
    credentials = self._get_credentials(kbb_dir)
  File "/home/username/src/kbb/kbb/kbb.py", line 91, in _get_credentials
    flow = client.flow_from_clientsecrets(client_secret_file, Kbb.SCOPES)
  File "/home/username/src/kbb/venv/lib/python3.4/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/username/src/kbb/venv/lib/python3.4/site-packages/oauth2client/client.py", line 2181, in flow_from_clientsecrets
    cache=cache)
  File "/home/username/src/kbb/venv/lib/python3.4/site-packages/oauth2client/clientsecrets.py", line 166, in loadfile
    return _loadfile(filename)
  File "/home/username/src/kbb/venv/lib/python3.4/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', '/home/username/.kbb/secrets/client_secret.json', 'No such file or directory', 2)

**Comment by danobi** [comment]
Sorry, forgot to document this. `client_secrets.json` is a google api thing (see https://developers.google.com/api-client-library/python/guide/aaa_client_secrets ).

Sorry if I'm being pretty vague here, but it's been a while since I looked at this code. That being said, I remember I was very careful about making this code really readable. If you look in `kbb/kbb.py` I'm sure you can figure out what's going on.

**Comment by dset0x** [comment]
That's understandable. I realized GTasks integration was important to the project, but not that it was necessary for it to work. Thank you for your quick reply.
